export const GET_ALL_ORDERS_START = 'GET_ALL_ORDERS_START'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_ERROR = 'GET_ALL_ORDERS_ERROR'

export const CREATE_ORDERS_START = 'CREATE_ORDERS_START'
export const CREATE_ORDERS_SUCCESS = 'CREATE_ORDERS_SUCCESS'
export const CREATE_ORDERS_ERROR = 'CREATE_ORDERS_ERROR'

export const UPDATE_ORDER_START = 'UPDATE_ORDER_START'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR'

export const DELETE_ORDER_START = 'DELETE_ORDER_START'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR'