export const GET_ALL_ORDERS_START = 'GET_ALL_ORDERS_START'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_ERROR = 'GET_ALL_ORDERS_ERROR'

export const CREATE_ORDERS_START = 'CREATE_ORDERS_START'
export const CREATE_ORDERS_SUCCESS = 'CREATE_ORDERS_SUCCESS'
export const CREATE_ORDERS_ERROR = 'CREATE_ORDERS_ERROR'