export const GET_ALL_ORDERS_START = 'GET_ALL_ORDERS_START'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_ERROR = 'GET_ALL_ORDERS_ERROR'

export const CREATE_ORDERS_START = 'CREATE_ORDERS_START'
export const CREATE_ORDERS_SUCCESS = 'CREATE_ORDERS_SUCCESS'
export const CREATE_ORDERS_ERROR = 'CREATE_ORDERS_ERROR'

export const UPDATE_ORDER_START = 'UPDATE_ORDER_START'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR'

export const UPDATE_ORDER_STATUS_START = 'UPDATE_ORDER_STATUS_START'
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS'
export const UPDATE_ORDER_STATUS_ERROR = 'UPDATE_ORDER_STATUS_ERROR'

export const DELETE_ORDER_START = 'DELETE_ORDER_START'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR'

export const GET_ALL_ORDER_LIST_START = 'GET_ALL_ORDER_LISTSTART'
export const GET_ALL_ORDER_LIST_SUCCESS = 'GET_ALL_ORDER_LIST_SUCCESS'
export const GET_ALL_ORDERS_LIST_ERROR = 'GET_ALL_ORDER_LIST_ERROR'

export const GET_FILTER_ORDERS_START = 'GET_FILTER_ORDERS_START'
export const GET_FILTER_ORDERS_SUCCESS = 'GET_FILTER_ORDERS_SUCCESS'
export const GET_FILTER_ORDERS_ERROR = 'GET_FILTER_ORDERS_ERROR'

export const GET_SINGLE_ORDERS_START = 'GET_SINGLE_ORDERS_START'
export const GET_SINGLE_ORDERS_SUCCESS = 'GET_SINGLE_ORDERS_SUCCESS'
export const GET_SINGLE_ORDERS_ERROR = 'GET_SINGLE_ORDERS_ERROR'

export const GET_ALL_TRACKERS_ORDERS_START = 'GET_ALL_TRACKERS_ORDERS_START'
export const GET_ALL_TRACKERS_ORDERS_SUCCESS = 'GET_ALL_TRACKERS_ORDERS_SUCCESS'
export const GET_ALL_TRACKERS_ORDERS_ERROR = 'GET_ALL_TRACKERS_ORDERS_ERROR'

export const ON_PAGE_CHANGE_START = 'ON_PAGE_CHANGE_START'
export const ON_PAGE_CHANGE_SUCCESS = 'ON_PAGE_CHANGE_SUCCESS'
export const ON_PAGE_CHANGE_ERROR = 'ON_PAGE_CHANGE_ERROR'
