export const LOGIN_USERS_START = 'LOGIN_USERS_START'
export const LOGIN_USERS_SUCCESS = 'LOGIN_USERS_SUCCESS'
export const LOGIN_USERS_ERROR = 'LOGIN_USERS_ERROR'

export const GET_ALL_USERS_START = 'GET_ALL_USERS_START'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR'

